[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.19"
gas_limit = 10000000
gas_price = 1000000

[rpc_endpoints]
rise = "${RPC_URL}"

[etherscan]
rise = { key = "", url = "${EXPLORER_URL}/api/v1" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
